-- Job Radar - Supabase/PostgreSQL initial schema
-- Migration 001
-- Run once in Supabase SQL Editor.

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null unique,
  website text,
  linkedin_url text,
  logo_url text,
  sector text,
  location text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sources (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  source_type text,
  enabled boolean not null default true
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  public_id text not null unique,
  company_id bigint references public.companies(id) on delete set null,
  title text,
  location text,
  workplace_type text,
  description text,
  salary_text text,
  salary_min numeric,
  salary_max numeric,
  salary_currency text,
  salary_period text,
  status text not null default 'NEW',
  status_reason text,
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.searches (
  id bigint generated by default as identity primary key,
  public_id text not null unique,
  source_id bigint not null references public.sources(id),
  name text,
  keywords text,
  location text,
  date_filter text,
  remote_filter text,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.runs (
  id bigint generated by default as identity primary key,
  public_id text not null unique,
  search_id bigint references public.searches(id),
  source_id bigint not null references public.sources(id),
  started_at timestamptz not null,
  finished_at timestamptz,
  status text not null,
  records_found integer not null default 0,
  unique_records integer not null default 0,
  new_jobs integer not null default 0,
  known_jobs integer not null default 0,
  detail_errors integer not null default 0,
  truncated boolean not null default false,
  processed boolean not null default false,
  error_type text,
  error_description text,
  raw_file text
);

create table if not exists public.job_sources (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  source_id bigint not null references public.sources(id),
  external_job_id text not null,
  source_url text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  seen_count integer not null default 1,
  active boolean not null default true,
  unique(source_id, external_job_id)
);

create table if not exists public.ai_evaluations (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  evaluated_at timestamptz not null default now(),
  model_version text,
  decision text,
  score numeric,
  profile_match numeric,
  technical_match numeric,
  management_match numeric,
  sector_match numeric,
  seniority_match numeric,
  strengths jsonb,
  weaknesses jsonb,
  reasoning jsonb,
  created_at timestamptz not null default now()
);

-- Simplified human state: interest is only INTERESTED / NOT_INTERESTED.
-- applied is a true/false toggle independent from interest.
create table if not exists public.user_job_feedback (
  id bigint generated by default as identity primary key,
  job_id bigint not null unique references public.jobs(id) on delete cascade,
  interest text check (interest in ('INTERESTED','NOT_INTERESTED')),
  applied boolean not null default false,
  application_date timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  status text not null,
  application_date timestamptz,
  channel text,
  contact_name text,
  contact_role text,
  next_action text,
  next_action_date timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Tombstone/archive for jobs deliberately removed by the user.
-- This survives deletion from jobs and blocks the same vacancy from re-entering the Radar.
create table if not exists public.treated_jobs (
  id bigint generated by default as identity primary key,
  original_public_id text,
  source_code text not null,
  external_job_id text not null,
  source_url text,
  company_name text,
  job_title text,
  decision text not null default 'NOT_INTERESTED',
  ai_score numeric,
  ai_decision text,
  treated_at timestamptz not null default now(),
  unique(source_code, external_job_id)
);

create table if not exists public.job_events (
  id bigint generated by default as identity primary key,
  job_id bigint references public.jobs(id) on delete cascade,
  event_type text not null,
  event_date timestamptz not null default now(),
  old_value text,
  new_value text,
  reason text,
  actor text,
  created_at timestamptz not null default now()
);

create index if not exists idx_jobs_status on public.jobs(status);
create index if not exists idx_jobs_company on public.jobs(company_id);
create index if not exists idx_job_sources_job on public.job_sources(job_id);
create index if not exists idx_job_sources_source_external on public.job_sources(source_id, external_job_id);
create index if not exists idx_runs_search on public.runs(search_id, started_at);
create index if not exists idx_ai_job on public.ai_evaluations(job_id, evaluated_at desc);
create index if not exists idx_feedback_applied on public.user_job_feedback(applied);
create index if not exists idx_feedback_interest on public.user_job_feedback(interest);
create index if not exists idx_applications_job on public.applications(job_id);
create index if not exists idx_treated_source_external on public.treated_jobs(source_code, external_job_id);
create index if not exists idx_events_job on public.job_events(job_id, event_date desc);

insert into public.sources(code,name,source_type,enabled)
values ('linkedin','LinkedIn','job_board',true)
on conflict (code) do nothing;

-- Enable RLS now. Policies will be added in the next migration after we configure Auth.
alter table public.companies enable row level security;
alter table public.sources enable row level security;
alter table public.jobs enable row level security;
alter table public.searches enable row level security;
alter table public.runs enable row level security;
alter table public.job_sources enable row level security;
alter table public.ai_evaluations enable row level security;
alter table public.user_job_feedback enable row level security;
alter table public.applications enable row level security;
alter table public.treated_jobs enable row level security;
alter table public.job_events enable row level security;
