-- Job Radar - Learning V1
-- Purpose: observe user decisions without changing AI scoring yet.
-- Run this migration in Supabase SQL Editor after the previous migrations.

create table if not exists public.learning_signals (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  job_id bigint,
  signal_type text not null check (signal_type in ('INTERESTED','APPLIED','REJECTED')),
  signal_weight numeric(4,2) not null check (signal_weight >= -10 and signal_weight <= 10),
  reason text,

  -- Snapshot of the AI judgement at the moment the human signal is recorded.
  ai_decision text,
  ai_score numeric,
  ai_evaluation_id bigint,

  -- Snapshot of useful job context so learning survives later deletion/archiving.
  job_title text,
  company_name text,
  location text,
  workplace_type text,
  salary_text text,
  source_name text,

  -- Flexible extracted attributes for future learning without schema churn.
  job_features jsonb not null default '{}'::jsonb,
  ai_snapshot jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now()
);

create index if not exists learning_signals_user_created_idx
  on public.learning_signals (user_id, created_at desc);
create index if not exists learning_signals_job_idx
  on public.learning_signals (job_id);
create index if not exists learning_signals_type_idx
  on public.learning_signals (signal_type);

-- One current learned profile per user. V1 is observational: it stores conclusions,
-- evidence and confidence but does not automatically alter Gemini scoring.
create table if not exists public.learned_preferences (
  user_id uuid primary key default auth.uid(),
  profile_version integer not null default 1,
  sample_size integer not null default 0,
  positive_patterns jsonb not null default '[]'::jsonb,
  negative_patterns jsonb not null default '[]'::jsonb,
  uncertain_patterns jsonb not null default '[]'::jsonb,
  scoring_recommendations jsonb not null default '[]'::jsonb,
  summary text,
  generated_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.learning_signals enable row level security;
alter table public.learned_preferences enable row level security;

-- Authenticated users can only access their own learning data.
drop policy if exists learning_signals_select_own on public.learning_signals;
create policy learning_signals_select_own on public.learning_signals
for select to authenticated using (auth.uid() = user_id);

drop policy if exists learning_signals_insert_own on public.learning_signals;
create policy learning_signals_insert_own on public.learning_signals
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists learning_signals_update_own on public.learning_signals;
create policy learning_signals_update_own on public.learning_signals
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists learning_signals_delete_own on public.learning_signals;
create policy learning_signals_delete_own on public.learning_signals
for delete to authenticated using (auth.uid() = user_id);

drop policy if exists learned_preferences_select_own on public.learned_preferences;
create policy learned_preferences_select_own on public.learned_preferences
for select to authenticated using (auth.uid() = user_id);

drop policy if exists learned_preferences_insert_own on public.learned_preferences;
create policy learned_preferences_insert_own on public.learned_preferences
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists learned_preferences_update_own on public.learned_preferences;
create policy learned_preferences_update_own on public.learned_preferences
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

comment on table public.learning_signals is
'Human feedback signals used by Job Radar Learning. Observational in V1; does not directly change AI scoring.';
comment on table public.learned_preferences is
'Aggregated learned job preferences with evidence/confidence. V1 recommendations are not applied automatically.';
