-- Queue used by the Inbox 'Aplicar aprendizaje' button.
create table if not exists public.learning_reanalysis_requests(
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  status text not null default 'PENDING' check(status in ('PENDING','RUNNING','DONE','ERROR')),
  reviewed_count integer,
  archived_count integer,
  error_message text
);
alter table public.learning_reanalysis_requests enable row level security;
create policy "read own reanalysis requests" on public.learning_reanalysis_requests for select to authenticated using(auth.uid()=user_id);

create or replace function public.request_learning_reanalysis()
returns bigint language plpgsql security definer set search_path=public as $$
declare v_id bigint;
begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 -- One live request per user is enough: repeated clicks do not create a queue storm.
 select id into v_id from public.learning_reanalysis_requests
 where user_id=auth.uid() and status in ('PENDING','RUNNING') order by requested_at desc limit 1;
 if v_id is not null then return v_id; end if;
 insert into public.learning_reanalysis_requests(user_id) values(auth.uid()) returning id into v_id;
 return v_id;
end;$$;
revoke all on function public.request_learning_reanalysis() from public;
grant execute on function public.request_learning_reanalysis() to authenticated;
